アプリケーション作成
Misato0122/PomodoroTodo pull request #5
Opened 2020-12-22 00:41 UTC by Misato0122

### アプリケーション作成
*`rails new . --skip-test --skip-turbolinks`コマンドを実行しました。
*`rails 6.0.3`と`ruby 2.6.5`を使用
*`turbolinks`はJavascriptがうまく動作しない不具合が起きる可能性があるためスキップしています。
* MySQLを導入しています。
MysqlのDBのパスワードを環境変数で保管するため`dotenv`というgemを導入しています。
(https://qiita.com/noraworld/items/bfa80811c9e30b4474af)

### Gemの導入
* `rubocop`を導入し、`rubocop.yml`ファイルを作成。
* `better_errors` `binding_of_caller`を導入。
* PR雛形ファイルの追加。
* Rspec環境構築。

2020-12-22 05:30 UTC, yuji91 requested changes
https://github.com/Misato0122/PomodoroTodo/pull/5/files を見ると分かるのですが、
`vendor/bundle`以下のファイルがpushされているので確認お願いします！

2020-12-22 06:26 UTC, Misato0122 commented
vendor/bundle削除後、ローカルにて`bundle install --path vendor/bundle`コマンドを実行しています。ご確認お願いいたします。

2020-12-23 04:50 UTC, yuji91 requested changes
OKです！

`git add .`や`git add -A`を使う際には、コミットする前に`git status`で確認するようにしましょう。
`brew install tig`で`tig`を使うのも良いと思います。

2020-12-23 04:56 UTC, Misato0122 commented
変更を見やすくできるtigコマンドというものがあるのですね！使って見ます、ありがとうございます！

2020-12-23 04:56 UTC, merged